// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldackpvvrnanqoxiuagg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkYWNrcHZ2cm5hbnFveGl1YWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0OTU0NTYsImV4cCI6MjA4MDA3MTQ1Nn0.i4xdno2ljlRt6Foc0g6QR7vb3icWtXxBxzGWpoOcAKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});